### ISSUE TITLE
AssetValidator_AssetReferenceRestrictions error message popup after saving map

### ISSUE THREAD

**Issue by theMyll** [HeyZoos/OpenRTSCamera#24]
Hi, the camera is working fine but for some reason I see this error popup after I save the map: `Illegally references asset /OpenRTSCamera/BP_RTSCamera. You may only reference assets from EngineContent, Plugin:RoomGenerator, and ProjectContent here. (AssetValidator_AssetReferenceRestrictions)`. I just dismiss the message and the camera still works fine..

I have unzipped the code to MyProject\Plugins\GameFeatures\OpenRTSCamera, and I created a BP_MyRTSCamera blueprint which has the parent class BP_RTSCamera, and I have a RTSCameraBoundsVolume in the map.

**Comment by HeyZoos** [comment]
Hey, thanks for letting me know. I'll check it out soon 🙏
