### ISSUE TITLE
Set Active Camera

### ISSUE THREAD

**Issue by SagKun** [HeyZoos/OpenRTSCamera#32]
Hi, first of all I would like to say that this project is amazing and I would really like to use it in a game I'm trying to make and contribute to the code while I work on it.
I tried setting it up in the "top down" unreal engine template,
I read the "Getting Started" and I couldn't figure out where do I "Set Active Camera", I think there are some missing steps in the guide,
is it in the player controller blueprint? and if so do I need to add RTSCamera component to the player controller?(since the player controller doesn't have "set active camera" function)

**Comment by HeyZoos** [comment]
Hi! Sorry for such a delayed response. You can set it in the `BeginPlay` of your custom camera class itself and it should work. I'll update the documentation to be more explicit.

![image](https://github.com/HeyZoos/OpenRTSCamera/assets/9408481/eb03b16f-d2e4-4beb-b55c-13cd493fac2c)
